# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
# Vagrantfile - Servers' infrastructure
#
#
# Author: 	Rodrigo Alvares de Souza
# 			rsouza01@gmail.com
#
#
# History:
# Version 0.1: 2017/06/?? (rsouza) - First version.
# Version 0.2: 2017/06/17 (rsouza) - Refactoring / Using modules
#
#

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.librarian_puppet.puppetfile_dir = "librarian"

	# config.vm.box = "hashicorp/precise32"
	config.vm.box = "rsouza01/ubuntu_vagrant_box_16.04_LTS"
	# config.vm.box_version = "1.0.0"

	if Vagrant.has_plugin?("vagrant-librarian-puppet")
		config.librarian_puppet.puppetfile_dir = "librarian"
	end
	
	config.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm", :id, "--memory", "2048"]
	end

	config.vm.define :db do |db_config|
		db_config.vm.hostname = "db"
		db_config.vm.network :private_network, :ip => "192.168.33.10"

		db_config.vm.provision :"puppet" do |puppet|
      		puppet.module_path = ["modules", "librarian/modules"]
			
			puppet.manifests_path = "./manifests"
			puppet.manifest_file = "db.pp"
		end

	end

	config.vm.define :web do |web_config|
		web_config.vm.hostname = "web"
		web_config.vm.network :private_network, :ip => "192.168.33.12"

		web_config.vm.provision :"puppet" do |puppet|
      		puppet.module_path = ["modules", "librarian/modules"]
			puppet.manifests_path = "./manifests"
			puppet.manifest_file = "web.pp"
		end
	end

	config.vm.define :monitor do |monitor_config|
		monitor_config.vm.hostname = "monitor"
		monitor_config.vm.network   :private_network, :ip => "192.168.33.14"
	end

	config.vm.define :ci do |build_config|
		build_config.vm.hostname = "ci"
		build_config.vm.network :private_network, :ip => "192.168.33.16"
		build_config.vm.provision "puppet" do |puppet|
			puppet.module_path = ["modules", "librarian/modules"]
			puppet.manifest_file = "ci.pp"
		end
	end
end

